ALLDIRS=snake sncore
ALLINST=snake snscore

all:
	cd snake && make
	cd snscore && make

install:
	cd snake && make install
	cd snscore && make install

clean:
	cd snake && make clean
	cd snscore && make clean
