.TH PARANOIA 6
.SH NAME
paranoia \- simple adventure game
.SH SYNOPSIS
.B paranoia
.SH "DESCRIPTION"
This is a very simple, but amusing, adventure game. It is based on the
role-playing game "Paranoia". It requires no instructions, as it is self-
prompting. Note that since it uses random functions to simulate dice rolls,
it will choose its own pathways in some circumstances, unlike many
adventure games.
.SH AUTHOR
This manual page was written by Joey Hess,
for the Debian GNU/Linux system.
