all:
	cd canfield && make all
	cd cfscores && make all

install:
	cd canfield && make install
	cd cfscores && make install

clean:
	cd canfield && make clean
	cd cfscores && make clean

canfield:
	cd canfield && make all

cfscores:
	cd cfscores && make all
